name: gphotos-sync
base: core18 
adopt-info: gphotos-sync
summary: Google Photos Sync
description: |
  Google Photos Sync.

grade: stable
confinement: strict

parts:
  gphotos-sync:
    plugin: python
    source: https://github.com/gilesknap/gphotos-sync.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag | grep -v ^v | grep -v beta | sort -V | tail -n 1)"
      echo $last_committed_tag
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      echo $last_released_tag
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        echo "Setting version to $last_committed_tag"
        snapcraftctl set-version "${last_committed_tag}"
      else
        echo "Setting version to $(git rev-parse --short HEAD)"
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi

apps:
  gphotos-sync:
    command: gphotos-sync
    environment:
      LANG: C.UTF-
    plugs:
      - home
      - network
      - removable-media
      - mount-observe
